# frontend/Dockerfile
FROM node:18-alpine

WORKDIR /app

# only copy package files, install deps first
COPY package*.json ./
RUN npm install

# then copy the rest of your source
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
