version: "3.9"

services:
  api:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  web:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
