name: codex-multi-sprint
on:
  push:
    branches: [ "branch/multi-sprint" ]
jobs:
  codex-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt pytest openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - run: python orchestrator.py
